branch-defaults:
  master:
    environment: seetheissue-env
    group_suffix: null
  staging:
    environment: seetheissue
    group_suffix: null
global:
  application_name: seetheissue
  default_ec2_keyname: sti-production-instances
  default_platform: Ruby 2.2 (Puma)
  default_region: us-east-1
  profile: eb-cli
  sc: git
