# MySql
#
# Configure Using Gemfile
# gem 'mysql2'
#
default: &default
  adapter: mysql2
  encoding: utf8
  # For details on connection pooling, see rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  reaping_frequency: <%= ENV["DB_REAP_FREQ"] || 10 %>
  pool: <%= ENV["DB_POOL"] || ENV["MAX_THREADS"] || 5 %>
  port: 3306

development:
  <<: *default
  database: seetheissue_development
  host: localhost
  username: <%= ENV["DEVELOPMENT_DB_USER"] || "root" %>

  # The specified database role being used to connect to postgres.
  # To create additional roles in postgres see `$ createuser --help`.
  # When left blank, postgres will use the default role. This is
  # the same name as the operating system user that initialized the database.
  #username: ballot_ready

  # The password associated with the postgres role (username).
  #password:

  # Connect on a TCP socket. Omitted by default since the client uses a
  # domain socket that doesn't need configuration. Windows does not have
  # domain sockets, so uncomment these lines.
  #host: localhost

  # The TCP port the server listens on. Defaults to 5432.
  # If your server runs on a different port number, change accordingly.
  #port: 5432

  # Schema search path. The server defaults to $user,public
  #schema_search_path: myapp,sharedapp,public

  # Minimum log levels, in increasing order: #   debug5, debug4, debug3, debug2, debug1,
  #   log, notice, warning, error, fatal, and panic
  # Defaults to warning.
  #min_messages: notice

# Warning: The database defined as "test" will be erased and
# re-generated from your development database when you run "rake".
# Do not set this db to the same as development or production.
test: &test
  <<: *default
  database: seetheissue_test<%= ENV["TEST_ENV_NUMBER"] %>
  host: localhost
  username: <%= ENV["TEST_DB_USER"] || "root" %>
