# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 79ce4f34a9b1d0a0523f46bd2b3e9bf6d4689cf71a36c9d5ac0ab72ce110f11835d184dbedbdf6555a4d0814992fdc574de4d84c5c282d6cdea4829e9fdb248e

test:
  secret_key_base: 17166405b12d686076f68e3c5a7c14bb9b5cd6585d04bcdaa937558f1348c6791b9935a2fac8c78e9ba272b5a68f799ff4c977d37f0cf66eafe58fb655910ffa

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
